<Project Sdk="Godot.NET.Sdk/4.5.1">
    <Import Project="$(MSBuildThisFileDirectory)local.props" Condition="Exists('$(MSBuildThisFileDirectory)local.props')"/>
    
    <PropertyGroup>
        <ModId>Awakened</ModId>
        <ModName>$(ModId)</ModName>
        <AssemblyName>$(ModId)</AssemblyName>
        <PackFolders>Awakened</PackFolders>
        <!-- <IsStandaloneMod>true</IsStandaloneMod> -->
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="Downfall.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="AwakenedCode/**/*.cs" Exclude="AwakenedCode/Tests/**/*.cs"/>
        <AdditionalFiles Include="Awakened/**/*"/>
        <Using Include="Downfall.DownfallCode.Extensions"/>
    </ItemGroup>
    
    <ItemGroup Condition="'$(Submods)' != '' and $(Submods.Contains('Test'))">
        <Compile Include="AwakenedCode/Tests/**/*.cs"/>
    </ItemGroup>
</Project>
