<Project Sdk="Godot.NET.Sdk/4.5.1">
    <Import Project="$(MSBuildThisFileDirectory)local.props" Condition="Exists('$(MSBuildThisFileDirectory)local.props')"/>
    
    <PropertyGroup>
        <ModId>Champ</ModId>
        <ModName>$(ModId)</ModName>
        <AssemblyName>$(ModId)</AssemblyName>
        <PackFolders>Champ</PackFolders>
        <!-- <IsStandaloneMod>true</IsStandaloneMod> -->
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="Downfall.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Publicize Include="sts2:MegaCrit.Sts2.Core.Models.CardModel.BaseStarCost"/>
        <Publicize Include="sts2:MegaCrit.Sts2.Core.Models.CardModel._owner"/>
        <Publicize Include="sts2:MegaCrit.Sts2.Core.Combat.History.CombatHistory.Add"/>
        <Publicize Include="sts2:MegaCrit.Sts2.Core.Nodes.Combat.NCombatUi._energyCounter"/>
        <Publicize Include="sts2:MegaCrit.Sts2.Core.Nodes.HoverTips.NHoverTipSet.TextHoverTipDimensions"/>
    </ItemGroup>


    <ItemGroup>
        <Compile Include="ChampCode/**/*.cs" Exclude="ChampCode/Tests/**/*.cs"/>
        <AdditionalFiles Include="Champ/**/*"/>
        <Using Include="Downfall.DownfallCode.Extensions"/>
    </ItemGroup>

    <ItemGroup Condition="'$(Submods)' != '' and $(Submods.Contains('Test'))">
        <Compile Include="ChampCode/Tests/**/*.cs"/>
    </ItemGroup>
</Project>
