<Project Sdk="Godot.NET.Sdk/4.5.1">
    <Import Project="$(MSBuildThisFileDirectory)local.props" Condition="Exists('$(MSBuildThisFileDirectory)local.props')"/>
    
    <PropertyGroup>
        <ModId>Collector</ModId>
        <ModName>$(ModId)</ModName>
        <AssemblyName>$(ModId)</AssemblyName>
        <PackFolders>Collector</PackFolders>
        <IsStandaloneMod>true</IsStandaloneMod>
    </PropertyGroup>

    <ItemGroup>
        <None Include="Collector.json"/>
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="Downfall.csproj"/>
        <ProjectReference Include="SlimeBoss.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Publicize Include="sts2:MegaCrit.Sts2.Core.Combat.History.CombatHistory.Add"/>

        <Publicize Include="sts2:MegaCrit.Sts2.Core.Commands.Builders.AttackCommand+SourceType"/>
        <Publicize Include="sts2:MegaCrit.Sts2.Core.Commands.Builders.AttackCommand.Attacker"/>
        <Publicize Include="sts2:MegaCrit.Sts2.Core.Commands.Builders.AttackCommand.IsRandomlyTargeted"/>
        <Publicize Include="sts2:MegaCrit.Sts2.Core.Commands.Builders.AttackCommand.ModelSource"/>
        <Publicize Include="sts2:MegaCrit.Sts2.Core.Commands.Builders.AttackCommand._attackerAnimDelay"/>
        <Publicize Include="sts2:MegaCrit.Sts2.Core.Commands.Builders.AttackCommand._attackerAnimName"/>
        <Publicize Include="sts2:MegaCrit.Sts2.Core.Commands.Builders.AttackCommand._combatState"/>
        <Publicize Include="sts2:MegaCrit.Sts2.Core.Commands.Builders.AttackCommand._singleTarget"/>
        <Publicize Include="sts2:MegaCrit.Sts2.Core.Commands.Builders.AttackCommand._sourceType"/>

        <Publicize Include="sts2:MegaCrit.Sts2.Core.Models.CardModel._owner"/>


        <Publicize Include="sts2:MegaCrit.Sts2.Core.Nodes.Screens.CardLibrary.NCardLibrary.UpdateCardPoolFilter"/>
        <Publicize Include="sts2:MegaCrit.Sts2.Core.Nodes.Screens.CardLibrary.NCardLibrary._lastHoveredControl"/>
        <Publicize Include="sts2:MegaCrit.Sts2.Core.Nodes.Screens.CardLibrary.NCardLibrary._miscPoolFilter"/>
        <Publicize Include="sts2:MegaCrit.Sts2.Core.Nodes.Screens.CardLibrary.NCardLibrary._poolFilters"/>

    </ItemGroup>

    <ItemGroup>
        <Compile Include="CollectorCode/**/*.cs" Exclude="CollectorCode/Tests/**/*.cs"/>
        <AdditionalFiles Include="Collector/**/*"/>
        <Using Include="Downfall.DownfallCode.Extensions"/>
    </ItemGroup>
    
    <ItemGroup Condition="'$(Submods)' != '' and $(Submods.Contains('Test'))">
        <Compile Include="CollectorCode/Tests/**/*.cs"/>
    </ItemGroup>
</Project>
