<Project Sdk="Godot.NET.Sdk/4.5.1">
    <Import Project="build/mod.build.props" />
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
        <EnableDefaultNoneItems>false</EnableDefaultNoneItems>
        <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
        <NoWarn>$(NoWarn);STS002</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <AdditionalFiles Include="DataGen/localization/**/*.json"/>
        <Compile Remove="DataGen/**"/>
        <EmbeddedResource Remove="DataGen/**"/>
        <None Include="DataGen.json"/>
        <None Include="DataGen/**"/>
        <None Include="DataGenCode/**"/>
        <Compile Include="DataGenCode/**/*.cs"/>
    </ItemGroup>


    <ItemGroup>
        <ProjectReference Include="Downfall.csproj"/>
    </ItemGroup>
    <Import Project="mod.build.targets" />
</Project>