<Project>
    <PropertyGroup>
        <BaseIntermediateOutputPath>.godot\mono\temp\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
        <IntermediateOutputPath>.godot\mono\temp\obj\$(MSBuildProjectName)\$(Configuration)\</IntermediateOutputPath>
    </PropertyGroup>
    
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>14</LangVersion>

        <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
        <EnableDefaultNoneItems>false</EnableDefaultNoneItems>
        <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>

        <ImplicitUsings>true</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DefaultItemExcludes>
            packages/**;
            src/**;shaders/**;steam/**;System/**;themes/**;addons/**;
            animations/**;banks/**;debug_audio/**;fonts/**;images/**;
            localization/**;materials/**;models/**;RiderTestRunner/**;scenes/**
        </DefaultItemExcludes>
        <AppOutputBase>$(MSBuildProjectDirectory)\</AppOutputBase>

        <NoWarn>$(NoWarn);MSB3270;CS0436</NoWarn>
    </PropertyGroup>
    
    <PropertyGroup>
        <AssemblyVersion>0.1.20.0</AssemblyVersion>
        <FileVersion>0.1.20.0</FileVersion>
        <Version>0.1.20</Version>
        <BaseLibVersion>3.4.7</BaseLibVersion>
        <UseLocalBaseLib Condition="'$(UseLocalBaseLib)' == ''">false</UseLocalBaseLib>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <Optimize>false</Optimize>
        <DebugType>portable</DebugType>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <Optimize>true</Optimize>
        <DebugType>none</DebugType>
        <PathMap>$(AppOutputBase)=.\</PathMap>
    </PropertyGroup>
    
    <PropertyGroup>
        <IsWindows Condition="$([MSBuild]::IsOSPlatform('Windows'))">true</IsWindows>
        <IsLinux Condition="$([MSBuild]::IsOSPlatform('Linux'))">true</IsLinux>
        <IsOSX Condition="$([MSBuild]::IsOSPlatform('OSX'))">true</IsOSX>
    </PropertyGroup>
</Project>
