<Project Sdk="Godot.NET.Sdk/4.5.1">
    <Import Project="$(MSBuildThisFileDirectory)local.props" Condition="Exists('$(MSBuildThisFileDirectory)local.props')"/>

    <PropertyGroup>
        <ModId>Guardian</ModId>
        <ModName>$(ModId)</ModName>
        <AssemblyName>$(ModId)</AssemblyName>
        <PackFolders>Guardian</PackFolders>
        <!-- <IsStandaloneMod>true</IsStandaloneMod> -->
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="Downfall.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="GuardianCode/**/*.cs" Exclude="GuardianCode/Tests/**/*.cs"/>
        <AdditionalFiles Include="Guardian/**/*"/>
        <Using Include="Downfall.DownfallCode.Extensions"/>
    </ItemGroup>

    <ItemGroup Condition="'$(Submods)' != '' and $(Submods.Contains('Test'))">
        <Compile Include="GuardianCode/Tests/**/*.cs"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include=".godot\mono\temp\" />
    </ItemGroup>
</Project>
