<Project Sdk="Godot.NET.Sdk/4.5.1">
    <Import Project="$(MSBuildThisFileDirectory)local.props" Condition="Exists('$(MSBuildThisFileDirectory)local.props')"/>

    <PropertyGroup>
        <ModId>Hermit</ModId>
        <ModName>$(ModId)</ModName>
        <AssemblyName>$(ModId)</AssemblyName>
        <PackFolders>Hermit</PackFolders>
        <!-- <IsStandaloneMod>true</IsStandaloneMod> -->
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="Downfall.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Publicize Include="sts2:MegaCrit.Sts2.Core.Models.CardModel._owner"/>
        <Publicize Include="sts2:MegaCrit.Sts2.Core.Combat.History.CombatHistory.Add"/>

        <Publicize Include="sts2:MegaCrit.Sts2.Core.Commands.Builders.AttackCommand.IsRandomlyTargeted"/>
        <Publicize Include="sts2:MegaCrit.Sts2.Core.Commands.Builders.AttackCommand._combatState"/>
        <Publicize Include="sts2:MegaCrit.Sts2.Core.Commands.Builders.AttackCommand._singleTarget"/>

        <Publicize Include="sts2:MegaCrit.Sts2.Core.Nodes.Combat.NPlayerHand.RefreshLayout"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="HermitCode/**/*.cs" Exclude="HermitCode/Tests/**/*.cs"/>
        <AdditionalFiles Include="Hermit/**/*"/>
        <Using Include="Downfall.DownfallCode.Extensions"/>
    </ItemGroup>

    <ItemGroup Condition="'$(Submods)' != '' and $(Submods.Contains('Test'))">
        <Compile Include="HermitCode/Tests/**/*.cs"/>
    </ItemGroup>
</Project>
