<Project Sdk="Godot.NET.Sdk/4.5.1">
    <Import Project="$(MSBuildThisFileDirectory)local.props" Condition="Exists('$(MSBuildThisFileDirectory)local.props')"/>

    <PropertyGroup>
        <ModId>Hermit</ModId>
        <ModName>$(ModId)</ModName>
        <AssemblyName>$(ModId)</AssemblyName>
        <PackFolders>Hermit</PackFolders>
        <!-- <IsStandaloneMod>true</IsStandaloneMod> -->
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="Downfall.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="HermitCode/**/*.cs" Exclude="HermitCode/Tests/**/*.cs"/>
        <AdditionalFiles Include="Hermit/**/*"/>
        <Using Include="Downfall.DownfallCode.Extensions"/>
    </ItemGroup>

    <ItemGroup Condition="'$(Submods)' != '' and $(Submods.Contains('Test'))">
        <Compile Include="HermitCode/Tests/**/*.cs"/>
    </ItemGroup>
</Project>
