using BaseLib.Utils;
using Champ.ChampCode.Cards;
using Champ.ChampCode.Cards.Basic;
using Champ.ChampCode.CustomEnums;
using Champ.ChampCode.Interfaces;
using Champ.ChampCode.Events;
using Champ.ChampCode.Extensions;
using Champ.ChampCode.History;
using Champ.ChampCode.Powers;
using Champ.ChampCode.Stance;
using MegaCrit.Sts2.Core.Combat;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.CardPools;

namespace Champ.ChampCode.Core;

public class ChampCmd
{
    public static async Task EnterBerserkerStance(PlayerChoiceContext ctx, Player player)
    {
        await ChampModel.SetStance<ChampBerserkerStance>(ctx, player);
    }

    public static async Task EnterDefensiveStance(PlayerChoiceContext ctx, Player player)
    {
        await ChampModel.SetStance<ChampDefensiveStance>(ctx, player);
    }

    public static async Task EnterUltimateStance(PlayerChoiceContext ctx, Player player, AbstractModel source,
        int turns = 1)
    {
        await PowerCmd.Apply<UltimateStancePower>(ctx, player.Creature, turns, player.Creature, source as CardModel);
    }

    private static async Task EnterStance<T>(PlayerChoiceContext ctx, Player player) where T : ChampStanceModel
    {
        await ChampModel.SetStance<T>(ctx, player);
    }

    public static async Task EnterDifferentStance(PlayerChoiceContext ctx, Player owner)
    {
        var stance = owner.ChampStance;
        switch (stance)
        {
            case ChampBerserkerStance:
                await EnterDefensiveStance(ctx, owner);
                break;
            case ChampDefensiveStance:
                await EnterBerserkerStance(ctx, owner);
                break;
            default:
                await EnterRandomStance(ctx, owner);
                break;
        }
    }

    public static async Task EnterRandomStance(PlayerChoiceContext ctx, Player owner)
    {
        var rng = owner.Creature.CombatState!.RunState.Rng.CombatCardSelection;
        if (rng.NextBool())
            await EnterDefensiveStance(ctx, owner);
        else
            await EnterBerserkerStance(ctx, owner);
    }

    public static async Task ClearStance(PlayerChoiceContext ctx, Player player)
    {
        await ChampModel.SetStance<ChampNoStance>(ctx, player);
    }

    /// <summary>
    /// Whether a Finisher card would act right now: the stance has a Finisher, or a hook (e.g. Signature) allows it without one.
    /// Playability, glow and <see cref="PlayFinisher"/> all use this so the UI cannot disagree with the effect.
    /// </summary>
    public static bool FinisherCanAct(CardModel card)
    {
        if (!card.Tags.Contains(ChampTag.Finisher) || card._owner == null || card.CombatState is not { } cs)
            return false;
        return card.Owner.ChampStance.HasFinisher || ChampHook.AllowFinisherWithoutStance(cs, card);
    }

    /// <summary>Runs <paramref name="effect"/> only while a Berserker combo would trigger. Called by a card's
    /// own OnPlayInternal; the card still has to <see cref="ChampCardModel.WithBerserkerCombo"/> itself for the
    /// glow/tip to show.</summary>
    public static async Task BerserkerCombo(CardPlay cardPlay, Func<Task> effect)
    {
        if (cardPlay.Card.Owner.ShouldBerserkerComboTrigger)
            await effect.Invoke();
    }

    /// <summary>Runs <paramref name="effect"/> only while a Defensive combo would trigger. Called by a card's
    /// own OnPlayInternal; the card still has to <see cref="ChampCardModel.WithDefensiveCombo"/> itself for the
    /// glow/tip to show.</summary>
    public static async Task DefensiveCombo(CardPlay cardPlay, Func<Task> effect)
    {
        if (cardPlay.Card.Owner.ShouldDefensiveComboTrigger)
            await effect.Invoke();
    }

    /// <summary>Forces the stance's skill bonus for a card that isn't itself a Skill (e.g. the Echo strikes
    /// generated by TripleStrike), which otherwise only triggers via charge consumption in
    /// <see cref="ChampModel.BeforeCardPlayed"/>.</summary>
    public static async Task TriggerSkillBonusIfKeyworded(PlayerChoiceContext ctx, CardModel card)
    {
        if (card.Keywords.Contains(ChampKeyword.TriggerSkillBonus))
            await card.Owner.ChampStance.SkillBonus(ctx);
    }

    internal static async Task PlayFinisher(PlayerChoiceContext ctx, CardPlay cardPlay, FinisherDescriptor finisher)
    {
        var player = cardPlay.Card.Owner;
        var m = player.ChampStance;
        var combatState = player.Creature.CombatState!;
        if (!FinisherCanAct(cardPlay.Card)) return;
        var affectsAllPlayers = finisher.AffectsAllPlayers;
        var repeat = finisher.Repeat;

        for (var i = 0; i < repeat; i++)
        {
            // A Finisher played without a stance (see IAllowFinisherWithoutStance): no stance effect, but it still counts as a Finisher.
            if (m.HasFinisher) await m.Finisher(ctx, affectsAllPlayers);
            await ChampHook.OnFinisher(combatState, ctx, cardPlay);
            // Recorded after the hooks so listeners can ask "is this the first Finisher this turn?" via FinisherEntry.
            CombatManager.Instance.History.Add(combatState,
                new FinisherEntry(cardPlay, player.Creature, combatState.RoundNumber, player.Creature.Side,
                    CombatManager.Instance.History, combatState.Players));
        }

        if (finisher.KeepsStance || ChampHook.KeepStanceAfterFinisher(combatState, cardPlay.Card)) return;
        await ClearStance(ctx, player);
        if (m is ChampUltimateStance)
            await EnterStance<ChampUltimateStance>(ctx, player);
    }


    public static async Task SelectStanceToEnter(PlayerChoiceContext ctx, Player owner)
    {
        var choices = new List<CardModel>
        {
            owner.Creature.CombatState!.CreateCard<StanceDanceBerserker>(owner),
            owner.Creature.CombatState!.CreateCard<StanceDanceDefensive>(owner)
        };

        var chosen = await CardSelectCmd.FromChooseACardScreen(ctx, choices, owner);
        if (chosen == null) return;
        switch (chosen)
        {
            case StanceDanceBerserker:
                await EnterBerserkerStance(ctx, owner);
                break;
            case StanceDanceDefensive:
                await EnterDefensiveStance(ctx, owner);
                break;
        }
    }
}

[Pool(typeof(TokenCardPool))]
public class StanceDanceBerserker() : ChampCardModel(-1, CardType.Skill, CardRarity.Token, TargetType.Self)
{
    public override string CustomPortraitPath => ModelDb.Card<BerserkersShout>().CustomPortraitPath;
}

[Pool(typeof(TokenCardPool))]
public class StanceDanceDefensive() : ChampCardModel(-1, CardType.Skill, CardRarity.Token, TargetType.Self)
{
    public override string CustomPortraitPath => ModelDb.Card<DefensiveShout>().CustomPortraitPath;
}